# Generated by Django 4.2.3 on 2023-07-08 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('game_level', models.CharField(choices=[('L1', 'Level1'), ('L2', 'Level2'), ('SF', 'SemiFinal'), ('F', 'Final')], default='L1', max_length=2)),
                ('game_date', models.DateField()),
                ('venue', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('P', 'Pendig'), ('S', 'Started'), ('F', 'Finished')], default='P', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='LeagueAdmin',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=255)),
                ('total_score', models.IntegerField()),
                ('played_games', models.IntegerField()),
                ('team_avg', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('height_cm', models.IntegerField()),
                ('avg_score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('played_games', models.IntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.team')),
            ],
        ),
        migrations.CreateModel(
            name='GameTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Pendig'), ('W', 'Win'), ('L', 'LOOS'), ('D', 'Draw')], default='P', max_length=1)),
                ('team_score', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.team')),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GamePlayTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.team')),
            ],
            options={
                'unique_together': {('game', 'team', 'player')},
            },
        ),
    ]
